# Generated by Django 6.0.6 on 2026-06-22 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generators_username', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_edited', models.DateTimeField(auto_now=True)),
                ('max_requests_per_day', models.PositiveBigIntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('creators_ip', models.CharField(default='NOIP', max_length=255)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_uri', models.CharField(max_length=255)),
                ('date_time_of_request', models.DateTimeField(auto_now_add=True)),
                ('request_full_details', models.TextField()),
                ('requesters_ip', models.CharField(default='NOIP', max_length=255)),
                ('http_status_code', models.CharField(default='200', max_length=3)),
                ('request_error_details', models.TextField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='tokens.token')),
            ],
            options={
                'ordering': ['-date_time_of_request'],
            },
        ),
    ]
